env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:vue/vue3-essential'
  - standard
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules:
  {
    'no-unused-vars': 0,
    'no-undef': 0,
    'func-call-spacing': 0,
    'no-useless-constructor': 0,
    '@typescript-eslint/no-unused-vars':
      [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_'
        }
      ],
    '@typescript-eslint/comma-dangle': ['error', 'never'],
    '@typescript-eslint/explicit-module-boundary-types': 0,
    '@typescript-eslint/ban-ts-comment': 0,
    '@typescript-eslint/ban-types': 0,
    '@typescript-eslint/no-explicit-any': 2,
    '@typescript-eslint/semi': ['error', 'never']
  }
